name: noteapp
description: A new Flutter project.

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  get_it: ^7.0.0
  go_router: ^6.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^6.0.5
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  sqflite_common_ffi_web: ^0.4.5+3
  sqlite3_flutter_libs: ^0.5.26
  universal_platform: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
